### ISSUE TITLE
Opening files from Home directory

### ISSUE THREAD

**Issue by stephenjudge** [keshavbhatt/PixelFx#1]
I've just installed the  PixelFX snap on Xubuntu 20.04 with the command 
`sudo snap install pixelfx`

I want to open a file to edit from the Pictures folder of my user Home directory. However when I either use the context menu from the file "Open with PixelFx" or when I use the Open button in the app, nothing happens. In the first instance PixelFx opens but the image does not open in it. In the second instance the pressing the Open button does not present an file selection dialogue.

Is there a command I neither to enable during the snap installation to allow access to files in the Home directory?

**Comment by keshavbhatt** [comment]
No, its not a installation issue. The file dialog issue and Open with pixelFx need to be fixed. For now if the native dialog is not opening when you click Open button from app, you can switch to use non native dialog from setting of application.

**Comment by keshavbhatt** [comment]
This is fixed in the latest version please update.
